export enum Example {
  AudioProcessing = 'audio_processing',
  Backdrop = 'backdrop',
  BackdropArea = 'backdrop_area',
  Clearcoat = 'clearcoat',
  Compute = 'compute',
  CubemapAdjustments = 'cubemap_adjustments',
  CubemapDynamic = 'cubemap_dynamic',
  CubemapMix = 'cubemap_mix',
  DepthTexture = 'depth_texture',
  Equirectangular = 'equirectangular',
  InstanceMesh = 'instance_mesh',
  InstanceUniform = 'instance_uniform',
  LightsCustom = 'lights_custom',
  LightsIesSpotlight = 'lights_ies_spotlight',
  LightsPhong = 'lights_phong',
  LightsSelective = 'lights_selective',
  LoaderGltf = 'loader_gltf',
  LoaderGltfIridescence = 'loader_gltf_iridescence',
  LoaderGltfSheen = 'loader_gltf_sheen',
  Materials = 'materials',
  MaterialsVideo = 'materials_video',
  Morphtargets = 'morphtargets',
  Particles = 'particles',
  Rtt = 'rtt',
  Sandbox = 'sandbox',
  Shadowmap = 'shadowmap',
  Skinning = 'skinning',
  SkinningInstancing = 'skinning_instancing',
  SkinningPoints = 'skinning_points',
  Sprites = 'sprites',
  TslEditor = 'tsl_editor',
  VideoPanorama = 'video_panorama',
}

export type ExampleName = keyof typeof Example;
